import type { DrawingPrompt } from "./game-types.js";

export const DRAWING_PROMPTS = [
  { id: "octopus-elegance", text: "Imagine une pieuvre plus ou moins élégante.", category: "élégant" },
  { id: "cabin-comfort", text: "Représente une cabane plus ou moins confortable.", category: "confortable" },
  { id: "dragon-power", text: "Invente un dragon plus ou moins puissant.", category: "puissant" },
  { id: "penguin-suspicion", text: "Dessine un pingouin plus ou moins suspect.", category: "suspect" },
  { id: "train-speed", text: "Crée un train plus ou moins rapide.", category: "rapide" },
  { id: "sandwich-appetite", text: "Compose un sandwich plus ou moins appétissant.", category: "appétissant" },
  { id: "lamp-modernity", text: "Imagine une lampe plus ou moins moderne.", category: "moderne" },
  { id: "witch-kindness", text: "Représente une sorcière plus ou moins sympathique.", category: "mignon" },
  { id: "island-danger", text: "Invente une île plus ou moins dangereuse.", category: "dangereux" },
  { id: "slipper-luxury", text: "Dessine une pantoufle plus ou moins luxueuse.", category: "luxueux" },
  { id: "alien-strangeness", text: "Crée un extraterrestre plus ou moins étrange.", category: "étrange" },
  { id: "vampire-fear", text: "Imagine un vampire plus ou moins effrayant.", category: "effrayant" },
  { id: "duck-humour", text: "Représente un canard plus ou moins drôle.", category: "drôle" },
  { id: "cloud-sadness", text: "Invente un nuage plus ou moins triste.", category: "triste" },
  { id: "bicycle-intelligence", text: "Dessine un vélo plus ou moins intelligent.", category: "intelligent" },
  { id: "crown-elegance", text: "Crée une couronne plus ou moins élégante.", category: "élégant" },
  { id: "sofa-comfort", text: "Imagine un canapé plus ou moins confortable.", category: "confortable" },
  { id: "hamster-power", text: "Représente un hamster plus ou moins puissant.", category: "puissant" },
  { id: "detective-suspicion", text: "Invente un détective plus ou moins suspect.", category: "suspect" },
  { id: "rocket-speed", text: "Dessine une fusée plus ou moins rapide.", category: "rapide" },
  { id: "soup-appetite", text: "Crée une soupe plus ou moins appétissante.", category: "appétissant" },
  { id: "school-modernity", text: "Imagine une école plus ou moins moderne.", category: "moderne" },
  { id: "goblin-cuteness", text: "Représente un gobelin plus ou moins mignon.", category: "mignon" },
  { id: "bridge-danger", text: "Invente un pont plus ou moins dangereux.", category: "dangereux" },
  { id: "tent-luxury", text: "Dessine une tente plus ou moins luxueuse.", category: "luxueux" },
  { id: "fish-strangeness", text: "Crée un poisson plus ou moins étrange.", category: "étrange" },
  { id: "scarecrow-fear", text: "Imagine un épouvantail plus ou moins effrayant.", category: "effrayant" },
  { id: "king-humour", text: "Représente un roi plus ou moins drôle.", category: "drôle" },
  { id: "sun-sadness", text: "Invente un soleil plus ou moins triste.", category: "triste" },
  { id: "backpack-intelligence", text: "Dessine un sac à dos plus ou moins intelligent.", category: "intelligent" },
  { id: "whale-elegance", text: "Crée une baleine plus ou moins élégante.", category: "élégant" },
  { id: "spaceship-comfort", text: "Imagine un vaisseau plus ou moins confortable.", category: "confortable" },
  { id: "fairy-power", text: "Représente une fée plus ou moins puissante.", category: "puissant" },
  { id: "neighbor-suspicion", text: "Invente un voisin plus ou moins suspect.", category: "suspect" },
  { id: "snail-speed", text: "Dessine un escargot plus ou moins rapide.", category: "rapide" },
  { id: "planet-appetite", text: "Crée une planète plus ou moins appétissante.", category: "appétissant" },
] as const satisfies readonly DrawingPrompt[];
